#! /usr/bin/python
'''
 *  $Id: JobOpt_RawSignal_fromHex, 2015-03-02 21:34:14 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
#-------------------------------------------------------------------
    NOTE:   input data is scientific binary data
'''

#-------------------------------------------------------------------
import os
import glob
import DMPSW                    # Load DAMPE software
import libDmpHex2Root as Hex2Root
import libDmpRec0_RawSignal as DmpRec0

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.SetEventNumber(40)     # default: -1
#DMPSW.Core.StartTime("2013-01-01 00:00:00")     # default: 2013-01-01 00:00:00
#DMPSW.Core.StopTime("2016-01-01 00:00:00")      # default: 2053-01-01 00:00:00
#DMPSW.Core.LogLevel("Debug")      # Value = {Error | Warning | Info | Debug}. default: Info.
#DMPSW.Core.LogHeader("On") # default: off

#DBase=DMPSW.WorkPath+"/run/BT"
#-------------------------------------------------------------------
# RootIOSvc options
#DMPSW.RootIOSvc.InputPath(DBase+"/sci")
#newestData=max(glob.iglob(DBase+"/sci/*.frd"),key=os.path.getctime)
inputFileName = "./A2Data00_20141118_214521.frd"
DMPSW.RootIOSvc.SetInputFile(inputFileName)
#DMPSW.RootIOSvc.OutputPath(DMPSW.WorkPath+"/run/data/cal/ped")
DMPSW.RootIOSvc.SetWriteList("Event/Rec0")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcAlgBT = Hex2Root.DmpAlgHex2Root()
rdcAlgBT.SetMode("EQM")
#rdcAlgBT.SetConnector("Psd",DMPSW.WorkPath+"/share/Connector/Psd/EQM")
#rdcAlgBT.SetConnector("Bgo",DMPSW.WorkPath+"/share/Connector/Bgo/EQM")
Rec0 = DmpRec0.DmpAlgRec0_RawSignal()

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcAlgBT)
DMPSW.AlgMgr.Append(Rec0)

def findPedFile(path,ID,ref_time):
        ped_time="0"
        ped_fn="NO"
        fNamoes=os.listdir(path)
        for fn in fNamoes:
                if (".ped" not in fn) or (ID not in fn):
                        continue
                fn_time = fn[13:21]
                fn_time = fn_time+fn[22:28]
                if (int(fn_time) <= int(ref_time) and int(fn_time) > int(ped_time)):
                        ped_time = fn_time
                        ped_fn = fn
        return ped_fn

inputStem = inputFileName.split("/")
inputStem = inputStem[-1]
inf_time = inputStem[9:17]
inf_time = inf_time+inputStem[18:24]
pedPath ="/home/chi/dmpwork/MyData/Calibration/DAMPE/Pedestal/"
for iD in ["Bgo","Psd","Stk","Nud"]:
        pedf = findPedFile(pedPath,iD,inf_time)
        Rec0.SetPedestalFile(iD,pedPath+pedf)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

